### ISSUE TITLE
Estimated time-line for code and weights?

### ISSUE THREAD

**Issue by vishaal27** [kohjingyu/gill#1]
Hey, thanks so much for your great work -- I enjoyed reading the paper! Do you have an estimated timeline for when you are planning to release the code and pre-trained weights for the model?

**Comment by kohjingyu** [comment]
Thanks for your interest! I'm hoping to get model weights and inference code up in the next week, and training/preprocessing/eval code in the 2-3 weeks after that.

**Comment by vishaal27** [comment]
Great thanks for the prompt response, looking forward to the release! :)
