### ISSUE TITLE
Error while loading the gill model

### ISSUE THREAD

**Issue by Aafiya-H** [kohjingyu/gill#12]
Hi @kohjingyu, thank you so much for this amazing work!
I am trying to replicate the results and I have been using the "GILL_Inference_Examples.ipynb" you have provided. While running the code to load the gill model, I encounter the following error message:

Code:
`model = models.load_gill(model_dir)`

Error:
KeyError                                  Traceback (most recent call last)
Cell In[2], line 3
      1 # Download the model checkpoint and embeddings to checkpoints/gill_opt/
      2 model_dir = 'checkpoints/gill_opt/'
----> 3 model = models.load_gill(model_dir)

File /home/wiseyak/aafiya/gill/gill/models.py:883, in load_gill(model_dir, load_ret_embs)
    881 for k, v in checkpoint['state_dict'].items():
    882     state_dict[k.replace('module.', '')] = v
--> 883 img_token_embeddings = state_dict['model.input_embeddings.weight'].cpu().detach()
    884 del state_dict['model.input_embeddings.weight']
    885 print("Extracted image token embeddings")

KeyError: 'model.input_embeddings.weight'

Could you please guide me on how to resolve this?

**Comment by ShengShi1024** [comment]
You need to download opt-6.7b in advance (https://huggingface.co/facebook/opt-6.7b/tree/main).
I have no problem running the code here.

**Comment by Aafiya-H** [comment]
Thanks @ShengShi1024 for the response. However, isn't there a checkpoint already in  the checkpoints/gill_opt folder? This error is from the pretrained_ckpt.pth.tar file in the aforementioned folder.
