### ISSUE TITLE
Is there a code to prune the pre-trained model to decision model?

### ISSUE THREAD

**Issue by shugerdou** [kohjingyu/gill#13]
The current code only supports to prune the trained model to pretrained ckpt. How can I get the decision ckpt? In addition, the script shall be `python scripts/prune_model_ckpt.py  runs/gill_exp`

**Comment by kohjingyu** [comment]
Ah, I realized we haven't uploaded the annotated PartiPrompts data to train a decision model. Currently, you cannot extract the decision model from the pretrained ckpt. You can still pass `decision_model_path=None` to load a different checkpoint, although such a model will not output a retrieval or generation decision.

https://github.com/kohjingyu/gill/blob/485c46ca11b8f5039b4b1b8c53fbdb95731f71f8/gill/models.py#L872

We'll try to get the annotations and training script up within the next week or so. Sorry about that!

**Comment by shugerdou** [comment]
Thank you!

**Comment by kohjingyu** [comment]
I've uploaded the PartiPrompts annotations we conducted, and a notebook to train a decision model (from a trained GILL model, so it will work if you trained your own version) here:

https://github.com/kohjingyu/gill/blob/main/TrainDecisionClassifier.ipynb

I'm closing this issue for now, but feel free to reopen if you run into any other difficulties training the model!
