### ISSUE TITLE
Question about the generation pipeline

### ISSUE THREAD

**Issue by avipartho** [kohjingyu/gill#14]
Hi @kohjingyu, what's `self.text_emb_layers` used for and how is it impacting [this line here](https://github.com/kohjingyu/gill/blob/485c46ca11b8f5039b4b1b8c53fbdb95731f71f8/gill/models.py#L467).

**Comment by kohjingyu** [comment]
`self.text_emb_layers` indicates from which LLM layers the hidden states should be extracted from (for the `[IMG]` embeddings). In the paper we used just the hidden states from the last layer, so we set this to be `[-1]`:

https://github.com/kohjingyu/gill/blob/485c46ca11b8f5039b4b1b8c53fbdb95731f71f8/gill/models.py#L30

But if you wanted to extract embeddings from multiple layers, e.g., the second last and last (`[-1, -2]`), you could probably edit this as such (and performance may be better, but we didn't try this in detail). If you change this, the pretrained checkpoints won't be compatible, and you would have to retrain the model though. Hope that clarifies!
