### ISSUE TITLE
Multimodal generation in one pass

### ISSUE THREAD

**Issue by avipartho** [kohjingyu/gill#17]
Hi, thanks for sharing this awesome work.

As I was trying your system more and more, a few questions popped up in my mind:

1. In my experience, I am seeing instances where the LLM starts generating text but instead of finishing the sentence, it generates `[IMG0]` token and then because of forcibly adding the remaining IMG tokens, that text output remains incomplete. Whatever text tokens the model generates after the first batch of [IMG] tokens are mostly garbage. How often have you encountered this in your experiments? What could be the possible solution?
2. I noticed that you had `sf=1.4` in your notebook for multimodal dialogue generation. How did you choose this hyper-parameter to balance the generation between text and image? Was it the same for the 4 examples in figure 5 from your paper? Same questions go for `num_words` and `min_word_tokens`.
3. Did you evaluate GILL's text generation ability on any task e.g. VQA or plan to do so in future?

**Comment by avipartho** [comment]
Thanks for your feedback. In the above code snippet, because of the conditions in line 517, this generate function will never add the remaining [IMG] tokens in a batch generation, right?

**Comment by kohjingyu** [comment]
That's correct, batch generation is not really supported in this function for this reason (It might be good to add an assert here that the input has batch size = 1...), and it's tricky to get it working properly because of different sequence lengths.

**Comment by avipartho** [comment]
Adding an assertion here will break validation as during validation, your script uses the generate function on a batch.
https://github.com/kohjingyu/gill/blob/4a0a4ef7079d7e58cc7990753f5356e14bbd4bb8/gill/validate.py#L177
For the same reasons I have noticed that the sample generated examples from here actually have only `[IMG0]` token.
https://github.com/kohjingyu/gill/blob/4a0a4ef7079d7e58cc7990753f5356e14bbd4bb8/gill/validate.py#L188-L189

**Comment by kohjingyu** [comment]
Ah yes, you're right, I was thinking about adding it to `generate_for_images_and_texts()`.

> For the same reasons I have noticed that the sample generated examples from here actually have only [IMG0] tokens (if any).

This is true, but I think for generating captions / VQA results it does not really matter, since we only want the text, and not images. So in these cases you would always set `min_word_tokens` to be the same as `num_words`, so that IMG tokens don't appear. I think this would be the main use case for batched inference. Since you never produce images it would be much easier to handle batches > 1.
