### ISSUE TITLE
Queries regarding the Precomputed Text Embeddings

### ISSUE THREAD

**Issue by VIROBO-15** [kohjingyu/gill#19]
Dear Authors,

I found your work very interesting. Can you please clarify how are the text embedding generated and what text encoder of stable diffusion is used like "openai/clip-vit-base-patch32" or "openai/clip-vit-base-patch14" or something less. 
Or can you please provide the code of it.

**Comment by kohjingyu** [comment]
I think [this script](https://github.com/kohjingyu/gill/blob/e8a5d6ab4f5996bdb05760cf5b91ec16b126c679/scripts/preprocess_sd_embeddings.py) is what you are looking for?
