### ISSUE TITLE
training setting for reproduce the paper

### ISSUE THREAD

**Issue by sungonce** [kohjingyu/gill#21]
Hi. Thank you for sharing your great research!
Your work is very inspiring.
I have a question about the training settings in the code to reproduce your paper.

Here's what your paper says:
We trained the model with batch size 180 for 1 epoch (18000 iterations) on 1 A6000 GPU (24 clock hours).

and parameters in your code are defined by follows (main.py):
parser.add_argument('--epochs', default=90, type=int, metavar='N',
            help='number of total epochs to run')
  parser.add_argument('--steps_per_epoch', default=2000, type=int, metavar='N',
            help='number of training steps per epoch')
  parser.add_argument('--start-epoch', default=0, type=int, metavar='N',
            help='manual epoch number (useful on restarts)')
  parser.add_argument('--val_steps_per_epoch', default=-1, type=int, metavar='N',
            help='number of validation steps per epoch')
  parser.add_argument('-b', '--batch-size', default=200, type=int,
            metavar='N',
            help='mini-batch size (default: 200), this is the total '
               'batch size of all GPUs on the current node when '
               'using Data Parallel or Distributed Data Parallel')

I think there is a difference in the training parameters (especially batch size and iteration) between paper and code, can you clarify this?

**Comment by kohjingyu** [comment]
Hi, the training parameters detailed in Sec 3.4 (page 6) of the paper should be the same as the defaults in the code: 
<img width="893" alt="Screen Shot 2023-10-11 at 8 51 06 AM" src="https://github.com/kohjingyu/gill/assets/2196979/e4191d4c-71c6-4276-b377-32ed36c6e955">


I think the line you are referencing (batch size of 180 for 1 epoch) is from our [other paper Fromage](https://arxiv.org/abs/2301.13823). If you're interested in that work, the code is available in [this repo](https://github.com/kohjingyu/fromage).
