### ISSUE TITLE
Incorrect Loss Calculation in 'generation' Mode in validate.py

### ISSUE THREAD

**Issue by MiladMt11** [kohjingyu/gill#22]
![image](https://github.com/kohjingyu/gill/assets/90702922/7eb33c34-3085-479f-bff3-42d0d354e848)

Hello there! 👋 Thank you very much for this fascinating work
I think I noticed a small issue in the code. When model_mode is set to 'generation', the loss variable is being calculated using "args.ret_loss_scale", which seems to be incorrect. Shouldn't it use "args.gen_loss_scale" instead? I see no other reason for it to be set to retrieval loss.  :)

**Comment by kohjingyu** [comment]
Yes you're right, thanks for pointing this out! I've just fixed with e35e9779578a78d545010a50598647b1f519ab97. It doesn't matter for our results because ret_loss_scale == gen_loss_scale for the hyperparameters we use, though it will if you change the hyperparams.
