### ISSUE TITLE
Great Work!!! Need clarification for calculating the R@1 for retrieval

### ISSUE THREAD

**Issue by VIROBO-15** [kohjingyu/gill#23]
Hi Authors,

Can you please clarify or provide the code for reproducing the number of Table 5. 
I wanted the analyse the performance of the images tokens on retrieval head on [Img 0]----------------[IMG N]

**Comment by kohjingyu** [comment]
Hi, for table 5, you can reproduce the results by using the [VIST eval script](https://github.com/kohjingyu/fromage/blob/main/evals/eval_vist_retrieval.py) from the Fromage code. You probably need to edit some of the model calls to be suitable for GILL, but it should be fairly similar. Hope that helps!
