### ISSUE TITLE
Clarification on precomputing the visual embeddings

### ISSUE THREAD

**Issue by MiladMt11** [kohjingyu/gill#25]
Hi

I want to know about the precomputed visual embeddings that you are providing [here](https://drive.google.com/file/d/1e9Cimh2dpWN8Cbgx_mSR-954Dr-DS-ZO/view), how did you exactly compute these embeddings? maybe just using the same SD model on CC3M data?

Thanks in advance

**Comment by kohjingyu** [comment]
Hi, I realized this script wasn't added before, so here it is now: https://github.com/kohjingyu/gill/blob/main/scripts/extract_img_embs.py

This is not using SD, as these embeddings are for retrieval. Hope it helps!
