### ISSUE TITLE
How to get cc3m_embeddings

### ISSUE THREAD

**Issue by Control-derek** [kohjingyu/gill#26]
Hi Authors,

How did you get cc3m_embeddings.npy ? Do you use the trained vision encoder and linear project layer? Or you only use the method of  Vector database(I don't know about the Vector database at all)

Thank you!

**Comment by kohjingyu** [comment]
Hi, I realized this script wasn't added before, so here it is now: https://github.com/kohjingyu/gill/blob/main/scripts/extract_img_embs.py

Hope that helps!
