### ISSUE TITLE
release the evaluation code 

### ISSUE THREAD

**Issue by ytian8** [kohjingyu/gill#3]
Hey, thank you so much for the great work! I was wondering when will you release the evaluation code regarding to VIST dataset and the calculation of CLIP/ LPIPS scores. Thanks!

**Comment by kohjingyu** [comment]
Sorry for the delay! This should be released by the end of the week.

**Comment by ytian8** [comment]
Thank you so much!!

**Comment by kohjingyu** [comment]
The evaluation code for both the VIST and VisDial evals has been uploaded in the `evals/` folder, and instructions are provided in the README. Hope that helps!
