### ISSUE TITLE
GILL Image Retrieval Code on VIST

### ISSUE THREAD

**Issue by haochuan-li** [kohjingyu/gill#35]
Hi! Great work.

I want to reproduce the GILL results in Table 5.
<img width="380" alt="image" src="https://github.com/kohjingyu/gill/assets/65277376/524810f1-8265-4b1a-9dbf-4495e98bbd7a">

I'm wondering what code changes need to be done in [eval_vist_retrieval.py](https://github.com/kohjingyu/fromage/blob/main/evals/eval_vist_retrieval.py) from FROMAGe.

I've tried changing these lines([L135-L142](https://github.com/kohjingyu/fromage/blob/b36a1889e16cb9486e83e1853dce68ab653068c9/evals/eval_vist_retrieval.py#L135-L142) and [L154-L159](https://github.com/kohjingyu/fromage/blob/b36a1889e16cb9486e83e1853dce68ab653068c9/evals/eval_vist_retrieval.py#L154-L159)) but the results seem not quite right...

```python
"""L135-142"""
all_input_ids = []
for i, c in enumerate(captions):
    if i == len(captions) - 1:
        c += '[IMG]'     # c += '[RET]'  
    input_ids = model.model.tokenizer(c, add_special_tokens=True, return_tensors="pt").input_ids.to(emb_matrix.device)
    all_input_ids.append(input_ids)

input_embs = [model.model.input_embeddings(s)[0, ...] for s in all_input_ids]  # (N, T, D)

"""L154-159"""
output = model.model.lm(inputs_embeds=final_input_embs, labels=None, use_cache=False, output_hidden_states=True)
# last_hidden_state = model.model.text_hidden_fcs[0](output.hidden_states[-1])
last_hidden_state = model.model.ret_text_hidden_fcs[0](output.hidden_states[-1], None)
ret_emb = last_hidden_state[:, -1, :]

ret_emb = ret_emb / ret_emb.norm(dim=1, keepdim=True)
scores = ret_emb.squeeze() @ emb_matrix.squeeze().T

```

Looking forward to your reply.

Thanks.

**Comment by kohjingyu** [comment]
Hi, it looks like the reason is that you're adding `[IMG]`, but GILL expects `[IMG0]...[IMGr]`. You probably want to be adding `[IMG0]` instead of `[IMG]`. You can verify this by checking that it only adds a single token instead of multiple, since `[IMG0]` will be part of the vocab but `[IMG]` is not.

Since retrieval uses just the first IMG token, replacing `[IMG]` with `[IMG0]` in your code should be sufficient, I think.
