### ISSUE TITLE
Great Work!!!! Few Queries regarding the preprocessing of the data

### ISSUE THREAD

**Issue by VIROBO-15** [kohjingyu/gill#6]
Hey, thanks so much for your great work -- I enjoyed reading the paper! 
I had few queries regarding the preparation of the CC3M, 
Can you please provide the links to download the image and annotation. As In the website we can directly find the .tsv file

**Comment by kohjingyu** [comment]
Thanks for your interest. As we don't own any of the CC3M images, we cannot legally provide them to you. You'd have to download them using the URLs provided in the .tsv file, probably with a script [like this one](https://huggingface.co/spaces/flax-community/dalle-mini/commit/75b01a0a3a29bb2eb6962f5f2fdf160e5c784647).

**Comment by VIROBO-15** [comment]
Hi Kohjigyu,

I have downloaded the data from the script but still have some problem in data preparation. Can you please let me know how to make the .tsv file for the image and its caption. can you please provide the code for that
