### ISSUE TITLE
Query regarding the preprocessing of the data

### ISSUE THREAD

**Issue by VIROBO-15** [kohjingyu/gill#7]
Hi, 

Great work!!!!

After downloading the cc3m data and creating .tsv file I am getting the error 

Error reading for /home/mbzuaiser/gill/data/training/01963207---stock-photo-an-brazil-road-pare-stop-sign-with-a-sky-background-and-copy-space-for-your-message-110146604.jpg with caption a road pare stop sign with a sky background and copy space for your message: Failed to interpret file <_io.BufferedReader name='/home/mbzuaiser/gill/data/training/01963207---stock-photo-an-brazil-road-pare-stop-sign-with-a-sky-background-and-copy-space-for-your-message-110146604.jpg.npy'> as a pickle

Can you please help me in fixing this error

**Comment by kohjingyu** [comment]
Thanks for your interest! I've not seen this error before. Some things to check:

1) Did you run the [text embedding preprocessing script](https://github.com/kohjingyu/gill#precomputing-text-embeddings)?

2) Does the file `'/home/mbzuaiser/gill/data/training/01963207---stock-photo-an-brazil-road-pare-stop-sign-with-a-sky-background-and-copy-space-for-your-message-110146604.jpg.npy'` exist? Can you open it by running

```
with open('/home/mbzuaiser/gill/data/training/01963207---stock-photo-an-brazil-road-pare-stop-sign-with-a-sky-background-and-copy-space-for-your-message-110146604.jpg.npy', 'rb') as f:
    data = np.load(f, allow_pickle=True)
```

or does it cause an error?
