### ISSUE TITLE
Generated image quality

### ISSUE THREAD

**Issue by Epiphqny** [kohjingyu/gill#8]
Hi @kohjingyu , thanks for your awesome work and sharing the code, but I found that the generated image quality is not very good. Do I have any problem in running the code? such as "an astronaut riding a horse on mars", "an cat riding a horse on mars" and "an dog riding a horse on mars". The results are as follows: 

![astronaut2](https://github.com/kohjingyu/gill/assets/16319629/6e406cc2-e4ce-4dee-af83-eb5d72218bfd)
![cat2](https://github.com/kohjingyu/gill/assets/16319629/edf71056-8809-4630-a51e-e8ce9ea9dd6d)
![dog2](https://github.com/kohjingyu/gill/assets/16319629/3b973442-bedc-4a2e-aeb0-81b676e20d23)

The number of astronaut and the generated cat or dog is not correct, do you have any suggestions? Thanks very much!

**Comment by kohjingyu** [comment]
Hi, thanks for your interest! I think this level of output is somewhat expected. Your first image is the exact same as the one from our [notebook](https://github.com/kohjingyu/gill/blob/main/GILL_Inference_Examples.ipynb), so the model should be correct.

Note that the image generator being used here is Stable Diffusion v1.5 (which is worse than SDXL and models like DeepFloyd), so the image realism/quality (not semantic match, as explained in our paper) is somewhat upper bounded by that model. Hope that helps!

**Comment by kohjingyu** [comment]
Right now I don't have these planned for the near future, but in principle it should be quite easy to swap in stronger LLMs, like some of the instruction or dialogue fine-tuned one. From some conversations with others about the work, I think it's possible that some people are already working on this, so hopefully we might see something public soon!
